from setuptools import setup, find_packages

setup(
    name="cryptobot",
    version="1.0.0",
    description="A professional Solana trading bot with Streamlit dashboard",
    author="Etherlyweiner",
    author_email="etherlyweiner@example.com",
    packages=find_packages(where="src"),
    package_dir={"": "src"},
    install_requires=[
        "streamlit==1.26.0",
        "solana==0.28.1",
        "anchorpy==0.14.0",
        "solders==0.10.0",
        "aiohttp==3.9.3",
        "python-dotenv==1.0.0",
        "cryptography==42.0.5",
        "prometheus-client==0.20.0",
        "aiofiles==23.1.0",
        "nest-asyncio==1.5.7",
        "asyncio==3.4.3",
        "redis==5.0.1",
        "aioredis==2.0.1",
        "requests==2.31.0",
        "websockets>=9.0,<12.0",
        "pandas==2.2.0",
        "numpy==1.26.3",
        "ta==0.10.2",
        "fastapi==0.109.0",
        "uvicorn==0.27.0.post1",
        "psutil==5.9.8",
        "pywin32>=308",
        "python-json-logger==2.0.7",
        "plotly==5.16.1",
        "black==24.1.1",
        "isort==5.12.0",
        "flake8==6.1.0",
        "python-jose[cryptography]==3.3.0",
        "passlib==1.7.4",
        "bcrypt==4.1.2",
        "structlog==24.1.0"
    ],
    python_requires=">=3.10,<3.11",
    entry_points={
        "console_scripts": [
            "cryptobot=cryptobot.app:main",
        ],
    },
    classifiers=[
        "Development Status :: 4 - Beta",
        "Intended Audience :: Financial and Insurance Industry",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
        "Programming Language :: Python :: 3.10",
        "Topic :: Office/Business :: Financial :: Investment",
    ],
    include_package_data=True,
    package_data={
        "cryptobot": ["config/*.json", "assets/*"],
    },
)
