groups:
  - name: CryptoBot
    rules:
      - alert: HighCPUUsage
        expr: process_cpu_seconds_total > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High CPU usage detected
          
      - alert: HighMemoryUsage
        expr: process_resident_memory_bytes / process_virtual_memory_bytes * 100 > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High memory usage detected
          
      - alert: APILatencyHigh
        expr: http_request_duration_seconds > 2
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: API latency is high
          
      - alert: ErrorRateHigh
        expr: rate(http_requests_total{status=~"5.."}[5m]) > 5
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: High error rate detected
          
      - alert: TradingLossHigh
        expr: trading_daily_loss_percent > 5
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: Daily trading loss exceeds threshold
