# Photon DEX Trading Bot Configuration

# Wallet settings
wallet:
  primary_address: "4c4nUoSeQyyp5PhAzxPudKCtKwkrEvTqY8AZVrhqJUGG"  # Primary wallet
  secondary_address: "7YTZcHQGJuReSDrQVvPCAj8qyxPzaUexHdKcswrumoyc"  # Secondary wallet
  max_retries: 3  # Maximum number of connection retries
  network: "mainnet-beta"  # Solana network

# Network settings
network:
  RPC:
    endpoints:
      - "https://rpc.helius.xyz/?api-key=74d34f4f-e88d-4da1-8178-01ef5749372c"  # Helius API key
    maxRetries: 3
    retryDelay: 1000
    timeout: 30000
  cluster: "mainnet-beta"  # Using mainnet for production
  commitment: "confirmed"

# Risk management
risk:
  max_daily_loss: 5.0  # Maximum daily loss percentage
  max_trade_size: 0.5  # Maximum trade size in SOL
  min_liquidity_sol: 100  # Minimum liquidity required in SOL
  max_position_size_sol: 1.0  # Maximum position size in SOL
  max_daily_trades: 20  # Maximum trades per day
  max_open_positions: 5  # Maximum concurrent positions
  min_liquidity_usd: 100000  # Minimum USD liquidity
  blacklisted_tokens: []  # List of token addresses to avoid

# Token discovery
discovery:
  min_liquidity: 100  # Minimum liquidity in SOL
  min_holders: 100  # Minimum number of holders
  min_volume: 50  # Minimum 24h volume in SOL
  max_opportunities: 10  # Maximum number of opportunities to return
  scan_interval: 300  # Seconds between scans
  min_opportunity_score: 3.0  # Minimum score for valid opportunities

# Browser settings
browser:
  headless: false  # Run in headless mode
  user_data_dir: "C:/Users/Jonat/CryptoBot/browser_data"  # Browser profile directory
  connection_retries: 3  # Number of connection retries
  element_timeout: 30  # Seconds to wait for elements
