# Secure Configuration File
api_keys:
  helius:
    key: "74d34f4f-e88d-4da1-8178-01ef5749372c"
    rpc_url: "https://staked.helius-rpc.com?api-key=74d34f4f-e88d-4da1-8178-01ef5749372c"  # Using staked RPC URL
    standard_rpc: "https://mainnet.helius-rpc.com/?api-key=74d34f4f-e88d-4da1-8178-01ef5749372c"
    staked_rpc: "https://staked.helius-rpc.com?api-key=74d34f4f-e88d-4da1-8178-01ef5749372c"
    ws_url: "wss://mainnet.helius-rpc.com/?api-key=74d34f4f-e88d-4da1-8178-01ef5749372c"
    api_base: "https://api.helius.xyz/v0"
  birdeye:
    key: "YOUR_BIRDEYE_API_KEY"
    base_url: "https://public-api.birdeye.so"
  solscan:
    key: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjcmVhdGVkQXQiOjE3Mzg0OTIxOTc1OTUsImVtYWlsIjoiZXRoZXJseWNvbm5lY3RlZDExQHByb3Rvbm1haWwuY29tIiwiYWN0aW9uIjoidG9rZW4tYXBpIiwiYXBpVmVyc2lvbiI6InYyIiwiaWF0IjoxNzM4NDkyMTk3fQ.P_EMG0JRQX4acFFdBZh8qV8VCb9ldn8wQI4IohM8cEg"
    base_url: "https://public-api.solscan.io/v2"

network:
  name: "mainnet"
  rpc_endpoints:
    - "https://api.mainnet-beta.solana.com"
    - "https://solana-api.projectserum.com"
    
wallet:
  address: "7YTZcHQGJuReSDrQVvPCAj8qyxPzaUexHdKcswrumoyc"
  encryption_key: ""  # Will be auto-generated
  private_key_path: "secure_config/wallet.key"

trading:
  min_sol_balance: 0.05    # Minimum SOL balance to maintain
  position_size: 0.1       # Position size in SOL for each trade
  max_slippage: 1.0       # 1% maximum slippage
  cooldown_minutes: 60     # Minutes to wait between trades
  priority_fee: 10000     # Priority fee in lamports (0.00001 SOL)
  max_positions: 5        # Maximum number of concurrent positions
  max_trades_per_day: 10  # Maximum number of trades per day
  stop_loss: 5.0         # 5% stop loss
  take_profit: 10.0      # 10% take profit
  trailing_stop: 3.0     # 3% trailing stop
  order_timeout: 30      # Order timeout in seconds

monitoring:
  log_level: "INFO"
  metrics_port: 9090
  enable_prometheus: true
  enable_alerts: true
  
security:
  enable_encryption: true
  key_rotation_days: 30
  max_failed_attempts: 3
  lockout_minutes: 30
